# Generated by Django 4.1 on 2022-10-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Source', models.CharField(max_length=3)),
                ('Destination', models.CharField(max_length=3)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=20000000)),
                ('FX', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('DestinationAmount', models.DecimalField(decimal_places=2, max_digits=20000000)),
            ],
        ),
    ]
